name: C/C++ CI

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v5
    
    - name: make
      run: make
    
    - name: make check
      run: make check
    
    - name: make distcheck
      run: make distcheck
